$("#Dress").click(function(){
    $("#Dress-image").slideToggle();
});
$("#Carriage").click(function(){
    $("#Carriage-image").fadeToggle();
});
$("#Horses").click(function(){
    $("#Horse-image").toggle();
});    